### ISSUE TITLE
Table cell content with line breaks get placed in the wrong row if there's a page break

### ISSUE THREAD

**Issue by ulyngs** [rstudio/pagedown#299]
I've run into this problem a few times now and don't know what's causing it. Here's a minimal reproducible example:

````
---
output: pagedown::html_paged
---

```{r}
library(dplyr)

iris |> 
  mutate(Petal.Length = paste(Petal.Length, "here's a line<br>and here's another line")) |> 
  select(Sepal.Length, Petal.Length) |> 
  knitr::kable()
```
````

When a page break divides up the content in the cell, then the remaining cell content is erroneously placed in the first column instead of in the second column where it belongs:

<img width="572" alt="image" src="https://user-images.githubusercontent.com/23137032/193270324-d177ee85-9501-46fc-9d2d-40a4d38831ac.png">

Any idea of how to fix this?

**Comment by ulyngs** [comment]
Hmmm it seems it's actually not about the break tags, I get the same problem with regular content that overflows between pages:

<img width="646" alt="image" src="https://user-images.githubusercontent.com/23137032/193421462-249bf585-ae20-496f-b04d-5ac11f0ffd3d.png">


````
---
output: pagedown::html_paged
---

```{r, echo=FALSE, message=FALSE}
library(dplyr)

tibble(
  id = 1:100,
  content = "here's a line and here's another line and another one and some more amazing content and yet more and more and more"
) |> 
  knitr::kable()
```
````

**Comment by xvazquezc** [comment]
Same issue here. Any word from the devs?

**Comment by courtney-bryce-hilton** [comment]
+1 am having the same issue

**Comment by courtney-bryce-hilton** [comment]
For anybody needing a temporary hacky solution, I got it working for me by manually creating additional tables to ensure they never cross a page.

**Comment by ulyngs** [comment]
The workaround I use is to manually add a page break after the content in the last cell that fits on a page:

**styles.css**

```css
br.pageBreak { page-break-after: always; }
```

The you can add `<br class="pageBreak">` as the ending of content in the cell that's the last one to fit on the page.

In [`pagedownCV`](https://ulyngs.github.io/pagedownCV/) I added a [convenience function](https://ulyngs.github.io/pagedownCV/reference/manual_page_break_after_row.html) to insert this, but it still has to be applied manually -- I don't know a way to automatically detect whether a table will be broken apart

**Comment by ulyngs** [comment]
@cderv any chance you know some magical ways we might go around fixing this? :)

**Comment by cderv** [comment]
No I don't have a magical way sorry. First thing would need to check somehow if the error is still present with newer version of paged.js. 

Unfortunately, I can't spend much time on that, but happy to review any PR is anyone found how to fix that, even a temporary workaround to add. We'll then merge and do a release with pleasure.

Sorry for the inconvenience currently.

**Comment by ethanhurwitz** [comment]
+1, issue is still occurring.

**Comment by meefen** [comment]
+1. Is there a fix?

**Comment by ulyngs** [comment]
@cderv apologies for bumping this --- might you be able to provide some pointer about what I'd need to do check if the issue is present with the latest version of paged.js? 

Does `pagedown` simply include paged.js directly, such that all I need to do is to go directly to https://pagedjs.org and make a reprex with their latest source files? 

Or is pagedown doing some magic with it when including, so that I'd need to somehow change the version included within pagedown?

**Comment by yihui** [comment]
@ulyngs Christophe is currently on vacation. My short answer is that unfortunately, upgrading paged.js may not be straightforward. Please see #252. It seems we need to at least replace our footnote hacks #21 with paged.js's native footnote support, but I don't have much expertise on this (yet). That said, you can definitely try to upgrade paged.js and see if it just works. Actually I briefly tested the latest release of paged.js last week and ran into [a bug](https://github.com/pagedjs/pagedjs/pull/161), so I'd recommend that you try its latest beta release instead (which is currently https://unpkg.com/pagedjs@0.5.0-beta.1/dist/paged.polyfill.js).

**Comment by yihui** [comment]
Just FYI, I just spent a week on writing a significantly simplified version of `paged.js`, tentatively named [`pages.js`](https://github.com/yihui/misc.js/blob/main/js/pages.js). I have felt for a long time that paged.js is too sophisticated and also complicated in terms of fragmenting HTML content, and I've been wondering how well we could do if we simply avoid fragmenting individual HTML elements, e.g., don't split a paragraph at the bottom of a page into two pieces to fit two pages. With 180 lines of JS and 185 lines of CSS, I feel an HTML page with a linear structure (i.e., no or few nested elements) can be split into pages reasonably well. You can try to open https://yihui.org/litedown/ and press `p` to see an example. Of course, my rudimentary fragmentation "algorithm" will leave some white space at the bottom of pages, which is its major drawback, but personally I don't care much about the extra space.

When an element is longer than one page, pages.js will allocate multiple pages (depending on the height of the element) for it when printing to PDF, and I rely on the web browser's built-in fragmentation capability (which is quite amazing) to break the element.

Currently I've only tested it with **litedown** documents (which produce highly linear HTML output). In case you want to quickly test it:

```r
install.packages("litedown", repos = c("https://yihui.r-universe.dev", "https://cloud.r-project.org"))
```

Press the Knit button in RStudio or call `litedown::fuse()` to render the example:

````md
---
output:
  litedown::html_format:
    meta:
      css: ["default", "@pages"]
      js: ["@pages"]
knit: litedown:::knit
---

```{r, echo=FALSE}
I(data.frame(
  id = 1:100,
  content = "here's a line<br>and here's another line"
))
```
````

Then press `p` on the HTML output page (or if the page is opened in a browser, you can also try to print the page to PDF with `Cmd/Ctrl + P`, and the document will be automatically split into pages).

**Comment by ulyngs** [comment]
Super exciting work Yihui!! 

I couldn't get the example to work on my Mac though. For the example you gave, all the table content stays on a single page that's then cut off when printing to PDF from Chrome:

<img width="618" alt="Image" src="https://github.com/user-attachments/assets/7ea832a7-d02f-45da-8d99-0ce02fb548e2" />

Not sure if I'm doing something wrong here

**Comment by yihui** [comment]
@ulyngs Sorry, that's a bug in my CSS. I just fixed it.

**Comment by ulyngs** [comment]
That did the trick in print output:

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/9a4b8aff-fdd4-425b-866b-03518f332934" />

However, when viewing the HTML in chrome, I still get the table in one massive page with a scrollbar instead of being broken up across multiple pages:

![Image](https://github.com/user-attachments/assets/bf9380e7-c00d-4159-b50b-41d827029fad)

**Comment by ulyngs** [comment]
That works also when viewed in Chrome! 🥳

<img width="1291" alt="Image" src="https://github.com/user-attachments/assets/fcde5885-1348-43b9-a42d-e431f915e493" />

**Comment by yihui** [comment]
Yes, after finishing the tasks of fragmenting tables the other day and paragraphs today, I'm happy to announce that I have finished "reinventing (La)TeX" in the browser with less than 10Kb's CSS and JS. The current **litedown** book takes about half a second to fragment into ~150 A4 pages: https://yihui.org/litedown/ I've also done pressure testing on other lengthy pages and usually it should take no more than a few seconds. The fragmentation is not definitely perfect, but good enough to me. This is probably the most satisfactory by-product from developing **litedown**, and the JS code is not tied to **litedown** (although it does have some assumptions).
