### ISSUE TITLE
How to print a local HTML file?

### ISSUE THREAD

**Issue by yihui** [rstudio/pagedown#68]
`chrome_print('foo.html')` doesn't work, which is understandable, but `file://full/path/to/foo.html` doesn't work, either. So how can we print local HTML files?

Of course, we can launch a local server (e.g. `servr::httd()`), but I wonder if there are other ways.

**Comment by cderv** [comment]
Just to share that local printing is working for me on windows. It was working with `crrri` and I just check with `pagedown`
```r
pagedown::chrome_print('file:///C:/Users/chris/Documents/test.nb.html', verbose = T, browser = chrome_bin)
```
gets me a _test.nb.pdf_ file (in the current working directory... 🤔 )

**Comment by RLesur** [comment]
Same thing for me on ubuntu **only with self contained html document**.
```r
copy_template = function(name) {
  rmd_file = sprintf('%s.Rmd', name)
  file.copy(
    system.file('rmarkdown', 'templates', name, 'skeleton', 'skeleton.Rmd', package = 'pagedown', mustWork = T),
    rmd_file,
    overwrite = TRUE
  )
  rmd_file
}

print_template = function(name) {
  output = rmarkdown::render(copy_template(name))
  pagedown::chrome_print(paste0('file://', output), verbose = T)
}
```

This works well:
```r
print_template('business-card')
```

However, this does not work:
```r
print_template('html-paged')
```
This is due to security restrictions. Opening the `html-paged.html` file with Chrome, I get the following error:
```
Fetch API cannot load file:///home/.../html-paged_files/paged-0.1.4/css/default-fonts.css. 
URL scheme must be "http" or "https" for CORS request.
```

**Comment by cderv** [comment]
ok. there is something going on with local html and paged.js.
```r
pagedown::chrome_print('file:///C:/Users/chris/Documents/DEV_R/pagedown/inst/examples/index.html', verbose = T, browser = chrome_bin)
```
timeout because the `pagedownListener` binding event is not reveived. The js script are not correctly found and executed. 

So it is working for simple and standalone file, but not from html file that a ressource folder.

In fact the error comes from [CORS request](https://developer.mozilla.org/fr/docs/Web/HTTP/CORS) that does not support `file://` scheme but only http or https. I see those errors just if I am trying to open the local html file generated in chrome. I can't open it properly because the _Fetch api_ throws an error.

> paged.js:23887 Fetch API cannot load file:///C:/Users/chris/Documents/DEV_R/pagedown/inst/examples/index_files/paged-0.1/css/default-fonts.css. URL scheme "file" is not supported.


I think serving the local file may be the clever thing to do here. 

There is yet an option for chromium : `--allow-file-access-from-files` but is does not seem to help on this one as it does not seem to be chromium that blog but the fetch API. 

I will keep on digging.

**Comment by yihui** [comment]
PR #71 should fix this issue. @cderv Please also feel free to review the PR. Thanks!

**Comment by cderv** [comment]
Oh thanks! I did not had time during this week. Sorry for that.
Thanks @RLesur for the review.

**Comment by yihui** [comment]
No worries at all. Please don't feel obligated to any tasks I assign to you. If there is anything urgent, I'll just move on without waiting. Usually nothing is urgent, though.

**Comment by katedd** [comment]
Hi Everyone, I see that this issue is marked as fixed, but I am still getting the error:
[2021-07-27 09:20:17] [error] handle_read_frame error: asio.system:10054 (An existing connection was forcibly closed by the remote host.)

From this code: 
pagedown::chrome_print(input = tmp_html_cv_loc,
                       output = "cv.pdf")

Can you help? Thanks!

**Comment by cderv** [comment]
Hi @katedd , 

Can you open a new issue and give some more details on the content you are trying to print ? 

There could be several reason involved and we'll be better in a new thread to discuss it! Thanks!
